# FILE: tests/language/test_broadcast_filter.py
"""
Tests pour le filtrage et masquage dans les broadcasts.
"""

import pytest

from catnip import Catnip
from catnip.exc import CatnipTypeError


def exec_catnip(code):
    """Helper to execute Catnip code"""
    c = Catnip()
    c.parse(code)
    return c.execute()


class TestBroadcastFilter:
    """Tests pour le filtrage conditionnel .[if condition]"""

    def test_filter_with_comparison(self):
        """.[if > 5] filters elements > 5"""
        result = exec_catnip("data = list(3, 8, 2, 9, 5); data.[if > 5]")
        assert result == [8, 9]

    def test_filter_with_different_comparisons(self):
        """Test different comparison operators"""
        # >=
        result = exec_catnip("data = list(3, 8, 2, 9, 5); data.[if >= 5]")
        assert result == [8, 9, 5]

        # <
        result = exec_catnip("data = list(3, 8, 2, 9, 5); data.[if < 5]")
        assert result == [3, 2]

        # ==
        result = exec_catnip("data = list(3, 8, 2, 9, 5); data.[if == 5]")
        assert result == [5]

        # !=
        result = exec_catnip("data = list(3, 3, 3); data.[if != 3]")
        assert result == []

    def test_filter_with_lambda(self):
        """.[if (x) => { x % 2 == 0 }] filtre les nombres pairs"""
        result = exec_catnip("data = list(1, 2, 3, 4, 5, 6); data.[if (x) => { x % 2 == 0 }]")
        assert result == [2, 4, 6]

    def test_filter_chaining(self):
        """Chaining filter + map"""
        # Filter > 5 then multiply by 2
        result = exec_catnip("data = list(3, 8, 2, 9, 5); data.[if > 5].[* 2]")
        assert result == [16, 18]

    def test_filter_preserves_type_list(self):
        """Filtering preserves list type"""
        result = exec_catnip("data = list(1, 2, 3, 4); data.[if > 2]")
        assert isinstance(result, list)
        assert result == [3, 4]

    def test_filter_preserves_type_tuple(self):
        """Filtering preserves tuple type"""
        result = exec_catnip("data = tuple(1, 2, 3, 4); data.[if > 2]")
        assert isinstance(result, tuple)
        assert result == (3, 4)

    def test_filter_empty_result(self):
        """Filtering can yield an empty result"""
        result = exec_catnip("data = list(1, 2, 3); data.[if > 10]")
        assert result == []

    def test_filter_all_pass(self):
        """Filtering where all elements pass"""
        result = exec_catnip("data = list(1, 2, 3); data.[if > 0]")
        assert result == [1, 2, 3]


class TestBroadcastMask:
    """Tests for boolean mask indexing .[mask]"""

    def test_mask_basic(self):
        """Basic filtering by boolean mask"""
        result = exec_catnip("data = list(10, 20, 30); mask = list(True, False, True); data.[mask]")
        assert result == [10, 30]

    def test_mask_all_true(self):
        """Masque avec tous True"""
        result = exec_catnip("data = list(1, 2, 3); mask = list(True, True, True); data.[mask]")
        assert result == [1, 2, 3]

    def test_mask_all_false(self):
        """Masque avec tous False"""
        result = exec_catnip("data = list(1, 2, 3); mask = list(False, False, False); data.[mask]")
        assert result == []

    def test_mask_generated_from_broadcast(self):
        """Mask generated by a comparison broadcast"""
        # Build mask then apply it
        result = exec_catnip("data = list(3, 8, 2, 9, 5); mask = data.[> 5]; data.[mask]")
        assert result == [8, 9]

    def test_mask_reuse_on_multiple_collections(self):
        """Reuse a mask across collections"""
        code = """
        data1 = list(10, 20, 30, 40)
        data2 = list("a", "b", "c", "d")
        mask = data1.[> 20]
        result1 = data1.[mask]
        result2 = data2.[mask]
        tuple(result1, result2)
        """
        result = exec_catnip(code)
        assert result == ([30, 40], ["c", "d"])

    def test_mask_preserves_type_list(self):
        """Mask preserves list type"""
        result = exec_catnip("data = list(1, 2, 3); mask = list(True, False, True); data.[mask]")
        assert isinstance(result, list)

    def test_mask_preserves_type_tuple(self):
        """Mask preserves tuple type"""
        result = exec_catnip("data = tuple(1, 2, 3); mask = list(True, False, True); data.[mask]")
        assert isinstance(result, tuple)

    def test_mask_size_mismatch_error(self):
        """Error when mask and data have different sizes"""
        with pytest.raises(ValueError, match="size mismatch"):
            exec_catnip("data = list(1, 2, 3); mask = list(True, False); data.[mask]")

    def test_mask_invalid_type_error(self):
        """Error when mask is not boolean"""
        with pytest.raises(CatnipTypeError, match="must be.*bool"):
            exec_catnip("data = list(1, 2, 3); mask = list(1, 0, 1); data.[mask]")


class TestBroadcastMapVsFilter:
    """Tests pour distinguer map et filter"""

    def test_map_returns_booleans(self):
        """.[> 5] returns booleans (map)"""
        result = exec_catnip("data = list(3, 8, 2, 9, 5); data.[> 5]")
        assert result == [False, True, False, True, False]
        assert all(isinstance(x, bool) for x in result)

    def test_filter_returns_filtered_elements(self):
        """.[if > 5] returns filtered elements"""
        result = exec_catnip("data = list(3, 8, 2, 9, 5); data.[if > 5]")
        assert result == [8, 9]
        assert all(isinstance(x, int) for x in result)

    def test_map_then_multiply_gives_wrong_result(self):
        """Pitfall: map then multiply yields 0 and 2 instead of the numbers"""
        # False * 2 = 0, True * 2 = 2
        result = exec_catnip("data = list(3, 8, 2); data.[> 5].[* 2]")
        assert result == [0, 2, 0]

    def test_filter_then_multiply_gives_correct_result(self):
        """Correct : filtrer puis multiplier"""
        result = exec_catnip("data = list(3, 8, 2); data.[if > 5].[* 2]")
        assert result == [16]


class TestBroadcastEdgeCases:
    """Tests pour cas limites"""

    def test_filter_empty_list(self):
        """Filtrer liste vide"""
        result = exec_catnip("data = list(); data.[if > 5]")
        assert result == []

    def test_mask_empty_list(self):
        """Masque sur liste vide"""
        result = exec_catnip("data = list(); mask = list(); data.[mask]")
        assert result == []

    def test_filter_single_element_pass(self):
        """Filter a single element that passes"""
        result = exec_catnip("data = list(10); data.[if > 5]")
        assert result == [10]

    def test_filter_single_element_fail(self):
        """Filter a single element that does not pass"""
        result = exec_catnip("data = list(3); data.[if > 5]")
        assert result == []

    def test_complex_chaining(self):
        """Complex chaining: filter, map, filter, map"""
        code = """
        data = list(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
        result = data.[if > 3].[* 2].[if < 15].[+ 1]
        result
        """
        # > 3: [4,5,6,7,8,9,10]
        # * 2: [8,10,12,14,16,18,20]
        # < 15: [8,10,12,14]
        # + 1: [9,11,13,15]
        result = exec_catnip(code)
        assert result == [9, 11, 13, 15]
