// FILE: catnip_vm/src/ops/errors.rs
//! Shared error message constants -- single source in `catnip_core::arith`.

pub use catnip_core::arith::{
    ERR_BAD_UNARY_NEG, ERR_BAD_UNARY_NOT, ERR_BAD_UNARY_POS, ERR_CMP_GE, ERR_CMP_GT, ERR_CMP_LE, ERR_CMP_LT,
    ERR_FLOAT_DIV_ZERO, ERR_FLOAT_FLOORDIV_ZERO, ERR_FLOAT_MOD_ZERO, ERR_INT_DIV_ZERO, ERR_LEGACY_MATCH,
    ERR_NO_ACTIVE_EXCEPTION, ERR_UNSUPPORTED_ADD, ERR_UNSUPPORTED_BITAND, ERR_UNSUPPORTED_BITOR,
    ERR_UNSUPPORTED_BITXOR, ERR_UNSUPPORTED_COMPARISON, ERR_UNSUPPORTED_DIV, ERR_UNSUPPORTED_FLOORDIV,
    ERR_UNSUPPORTED_LSHIFT, ERR_UNSUPPORTED_MOD, ERR_UNSUPPORTED_MUL, ERR_UNSUPPORTED_POW, ERR_UNSUPPORTED_RSHIFT,
    ERR_UNSUPPORTED_SUB,
};
