// FILE: catnip_grammar/src/lib.rs
// Production `unsafe` blocks must carry a `// SAFETY:` justification.
#![cfg_attr(not(test), deny(clippy::undocumented_unsafe_blocks))]

use tree_sitter::Language;

pub mod node_kinds;
pub mod symbols;

extern "C" {
    fn tree_sitter_catnip() -> Language;
}

/// Get the Catnip tree-sitter Language.
pub fn get_language() -> Language {
    // SAFETY: `tree_sitter_catnip` is the C entry generated by tree-sitter; it takes
    // no arguments and returns a valid, statically-allocated `Language`.
    unsafe { tree_sitter_catnip() }
}
